### ISSUE TITLE
Auto play stops when switching tabs

### ISSUE THREAD

**Issue by jrtapper** [CSS-Tricks/AnythingSlider#635]
I am working on a new site for our company and the AnythingSlider is working well for us, but we have noticed something I have not seen mentioned anywhere else.  

We have an autoplay slider at the top of our page that when you switch to a different tab in Chrome or FF the animation stops.   (see b2b.hitchfinderstores.com for our development page)

Is this expected?  If so, is there some way to change this behavior?

Thanks!

**Comment by Mottie** [comment]
Hi!

Actually yes, the plugin uses the [javascript page visibility api](http://caniuse.com/#feat=pagevisibility) to stop the slide show when the browser loses focus ([code reference](https://github.com/CSS-Tricks/AnythingSlider/blob/master/js/jquery.anythingslider.js#L859-L863)). This was done to reduce the amount of processing that is done in the background when content is not visible. It might not be a big deal now since mobile devices are much more powerful and most browsers now automatically increase the time intervals in hidden tabs. 

Anyway, to get around this, set the [`autoPlayLocked` option](https://github.com/CSS-Tricks/AnythingSlider/wiki/Slideshow-Options#autoplaylocked-false) to `true`.

**Comment by jrtapper** [comment]
Great! Thanks!
