### ISSUE TITLE
playing vimeo iframe video doesn't stop slider autoplay

### ISSUE THREAD

**Issue by horacegrant** [CSS-Tricks/AnythingSlider#645]
hi,

i have used anythingslider in a project about 3 years ago and then it behaved like that:
when a vimeo iframe video was playing, the slider autoplay stopped.

but now this doesn't work anymore. i have googled for solutions but nothing worked.

it also happens in your video example:
http://css-tricks.github.io/AnythingSlider/video.html

can this be fixed again? this would be great. :)

**Comment by Mottie** [comment]
Hi @horacegrant!

Hmm, it doesn't look like the api changed; but the Vimeo embedded code still works LOL. 

Actually, there are also all kinds of error messages in the console window... so it looks like you might need to change the iframe to use `https` instead of `http`.

I don't have the time to test that right now, so if that doesn't work, I'll have to look at it again when I get some free time.

I really haven't been maintaining this plugin. I just noticed that I merged but never released the changes added in pull #604 from over 2 years ago. To be honest, I'm sure there are other video sliders out there that are much more efficient and lean than this one. I'm not saying that I won't fix it, but I may not be able to get to it until this weekend, or later.

**Comment by Mottie** [comment]
Actually, that looks like it fixed it: http://jsfiddle.net/Mottie/ycUB6/10729/

**Comment by horacegrant** [comment]
thanks for your response! :)

i got it working now. but there is a small problem. vimeo src by default is:

src="//player...

and this causes an error in the jquery.anythingslider.video.js script. if i add https: it works.

**Comment by Mottie** [comment]
Hmm, I just pushed a new release, but all it does it replace http with https... so maybe I'll just add a note saying it requires `https`
