### ISSUE TITLE
Can't just use CSS

### ISSUE THREAD

**Issue by JstrzAtW2M** [CSS-Tricks/AnythingSlider#649]
I don't like that the anything slider always adds fixed element rules. I'm working on a responsive site and it's causing a lot of issues. Is there a way to remove all added element styles and make it only use the CSS?

**Comment by Mottie** [comment]
Hi @jstrez77!

I'm not happy about it either, but please remember this code base was written before css3 was fully implemented. And since then, I haven't had the time to rewrite the code; I've only had time to fix bugs.

Someday, when I do have time, I look into rewriting the plugin, unless someone beats me to it; but until then I would recommend using a different slider that is more responsive.

**Comment by JamyGolden** [comment]
Closing since it's been a few years.
