### ISSUE TITLE
JW Player is not working

### ISSUE THREAD

**Issue by lenin-interware** [CSS-Tricks/AnythingSlider#657]
Hi, the demo of the integration with JW Player is not working: 

- http://jsfiddle.net/Mottie/ycUB6/93/

This is my enviroment:

- JW Player: 7.8.4
- AnythingSlider: 1.9.6
- jQuery: 1.12.4

The inclusion of JW Player has changed from this:
```
<script src="http://player.longtailvideo.com/jwplayer.js"></script>
```
To something like this:
```
<script src="//mywebsite.com/jwplayer/jwplayer.js"></script>
<script>jwplayer.key="ABCdeFG123456SeVenABCdeFG123456SeVen==";</script>
```

Please update the demo to see how it works now!

**Comment by Mottie** [comment]
Hi @lenin-interware!

The issue with the demo is that the files were still linked to `http://css-tricks.github.com`, they needed to changed to point to `https://css-tricks.github.io`.

The other problems I noted were:
* The JWPlayer url was invalid. They moved their site to jwplayer.com, so I used the [jsDelivr CDN instead](https://www.jsdelivr.com/projects/jwplayer)&dagger;
* In v7 of their API, the player state is returned in lower case, so to fix that I had to make two changes (adding `.toUpperCase()`) to the code to make it backwards compatible with older versions of JWPlayer: `jwplayer(v[0]).getState().toUpperCase() === 'PAUSED'` and `jwplayer(jwid).getState().toUpperCase() === 'PLAYING'`.

I have updated the [JWPlayer wiki instructions](https://github.com/CSS-Tricks/AnythingSlider/wiki/Video#jwplayer) and [the demo](http://jsfiddle.net/Mottie/j47zs3gj/).

&dagger; I'm really loving the jsDelivr CDN because you can add multiple files to your "collection" and it will serve all the selected files to you in one `<script>` tag, e.g. 
`https://cdn.jsdelivr.net/g/jwplayer@7.1.4,anythingslider@1.8.6(jquery.anythingslider.min.js+jquery.anythingslider.video.min.js+jquery.anythingslider.video.js)`

**Comment by lenin-interware** [comment]
Thanks! It works now like a charm!!
