### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by avisal** [CSS-Tricks/AnythingSlider#658]
Hi,

I want to know if there is a way that the AnythingSlider will load only a couple of slides on each time and not all of them in the first run?

Avi.

**Comment by Mottie** [comment]
Hi @avisal!

I'm not sure if you are referring to images or background images. Please check out the 3 demos under "Functionality" > "Lazy Image Loading" on the [Home](https://github.com/CSS-Tricks/AnythingSlider/wiki#functionality) wiki page.

**Comment by avisal** [comment]
I still don't get it. how it's work, it's always download all the picture and not only the image of the current slide, why?

I also look into the link, and I don't understand how it's work!

**Comment by Mottie** [comment]
I had to update the "image tags" demo - http://jsfiddle.net/Mottie/e1fno4ds/ - because it was using files from `http://css-tricks.github.com` instead of `https://css-tricks.github.io`.

Please take note that the `img`'s have a `data-src` attribute containing the image URL. The `src` attribute is an empty string.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
